include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve
  page_width: 79

analyzer:
  language:
    strict-casts: true
    strict-inference: true

  errors:
    invalid_annotation_target: ignore # freezed and json_serializable combination
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/l10n/gen/*

linter:
  rules:
    avoid_relative_lib_imports: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_breaks: true
    unnecessary_statements: true
    use_super_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
